fs = import('fs')

fs.copyfile('bindings.slang')
fs.copyfile('brdf.slang')
fs.copyfile('color.slang')
fs.copyfile('common.slang')
fs.copyfile('downsample.slang')
fs.copyfile('math.slang')
fs.copyfile('shaded.slang')
fs.copyfile('sky.slang')
fs.copyfile('tonemap.slang')
fs.copyfile('unlit.slang')
fs.copyfile('upsample.slang')
